version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - mongodbdata:/learnstack/db


  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=courses_db
      - MONGO_INITDB_ROOT_USERNAME=AdityaMeena
      - MONGO_INITDB_ROOT_PASSWORD=Aditya@3008
    ports:
      - 27018:27017

    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata: