pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/thoughtma/youtube-repo.git'
            }
        }

        stage('Build') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Test') {
            steps {
                sh 'python3 manage.py test'
            }
        }

        stage('Collect static files') {
            steps {
                sh 'python3 manage.py collectstatic --noinput'
            }
        }

        stage('Build Docker image') {
            steps {
                sh 'docker build -t learnstack_app .'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker run -d -p 8000:8000 learnstack_app'
            }
        }

        stage('Setup Ngrok') {
            steps {
                sh 'wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip'
                sh 'unzip ngrok-stable-linux-amd64.zip'
                sh './ngrok authtoken 2LMOSU10gLkwl6GsQhBH2C8t4hX_4nNWiJLEt2ZYw2m5bwQuh'
                sh './ngrok http 8000'
            }
        }
    }
}
