name: Learnstack Development

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download and extract ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip

      - name: Authenticate Ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          ./ngrok authtoken $NGROK_AUTH_TOKEN

      - name: Stop Ngrok
        run: |
          killall ngrok
          sleep 2

      - name: Start Ngrok and capture URL
        id: ngrok
        run: |
          ./ngrok http 8000 --region=us > ngrok-log.txt &
          sleep 10
          curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Display Ngrok URL
        run: |
          echo "Ngrok URL: ${{ steps.ngrok.outputs.stdout }}"
