name: Deploy to Serveo

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Change this to your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust this to your requirements file location

      - name: Start Django server
        run: |
          python manage.py runserver --noreload
        background: true

      - name: Deploy to Serveo
        run: |
          sleep 10  # Adjust the sleep duration as needed
          ssh -R 80:localhost:8000 -o "StrictHostKeyChecking=no" serveo.net
