name: Learnstack Development

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download and extract ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip

      - name: Authenticate Ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          ./ngrok authtoken $NGROK_AUTH_TOKEN

      - name: Debug - Print current working directory
        run: |
          pwd

      - name: Start Django server
        run: |
          cd learnstack
          python3 manage.py runserver 8000 &

      - name: Wait for Django server to start
        run: |
          sleep 20

      - name: Debug - List files in directory
        run: |
          ls -al

      - name: Set executable permissions for ngrok
        run: |
          chmod +x ngrok

      - name: Start Ngrok
        id: ngrok
        run: |
          ./ngrok http 8000 --host-header="localhost:8000" > ngrok_output.txt &

      - name: Debug - List files in directory
        run: |
          ls -al

      - name: Wait for Ngrok tunnel to be established
        run: |
          sleep 60
          while ! grep -q "https://.*ngrok.io" ngrok_output.txt; do
            sleep 10
          done

      - name: Get Ngrok URL
        run: |
          cat ngrok_output.txt | grep -o "https://.*ngrok.io" > ngrok_url.txt

      - name: Display Ngrok URL
        run: |
          cat ngrok_url.txt
