name: Learnstack Development

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download and extract ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip

      - name: Authenticate Ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          ./ngrok authtoken $NGROK_AUTH_TOKEN

      - name: Start Django server
        run: |
          cd ${{ github.workspace }}/learnstack
          python3 manage.py runserver 8000 &

      - name: Start Ngrok
        id: ngrok
        run: |
          sleep 15 # Wait for Django server to start
          ./ngrok http 8000 --host-header="localhost:8000" > ngrok_output.txt &

      - name: Wait for Ngrok URL
        id: wait_for_ngrok
        run: |
          sleep 10
          while ! curl -s http://localhost:4040/api/tunnels | grep -q "public_url"; do sleep 5; done

      - name: Get Ngrok URL
        run: |
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url' > ngrok_url.txt

      - name: Display Ngrok URL
        run: |
          cat ngrok_url.txt
