name: Deploy to Serveo

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Start Django server
        run: |
          cd learnstack
          nohup python manage.py runserver --noreload &
          sleep 15
          curl http://localhost:8000  

      - name: Deploy to Serveo
        run: |
          ssh -R 80:localhost:8000 -o "StrictHostKeyChecking=no" serveo.net
