name: Learnstack Development

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Ngrok
        run: |
          curl -L https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
          unzip ngrok.zip
      - name: Start Ngrok
        run: |
          ./ngrok http 8000 --region=us